services:
  aerooffers-frontend:
    build: ./frontend
    ports:
      - '8080:80'
    depends_on:
      - aerooffers-backend

  aerooffers-backend:
    build: ./backend
    ports:
      - '8081:80' # exposed for debugging and local frontend development without python
    environment:
      - DB_HOST=aerooffers-db
      - DB_PORT=5432
      - DB_NAME=aircraft_offers
      - DB_USER=aircraft_offers
      - DB_PW=aircraft_offers
    depends_on:
      - aerooffers-db

  aerooffers-db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=aircraft_offers
      - POSTGRES_USER=aircraft_offers
      - POSTGRES_PASSWORD=aircraft_offers
    ports:
      - '25432:5432'
    volumes:
      - ./db/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./db/prod_dump_2024_06_31.sql:/docker-entrypoint-initdb.d/prod_dump_2024_06_31.sql
