services:
  ca-aerooffers-api:
    build: ./backend
    ports:
      - '8082:80' # exposed for debugging and local UI development without python
    environment:
      - 'COSMOSDB_URL=http://cosmosdb:8081'
      - 'COSMOSDB_CREDENTIAL=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=='
      - 'COSMOSDB_DB_NAME=aerooffers'
    depends_on:
      - cosmosdb

  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
    environment:
      - 'AZURE_COSMOS_EMULATOR_KEY=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=='
    ports:
      - '8081:8081'
      - '1234:1234' # admin ui