services:
  ca-aerooffers-ui:
    build: ./frontend
    ports:
      - '8080:80'
    depends_on:
      - ca-aerooffers-api

  ca-aerooffers-api:
    build: ./backend
    ports:
      - '8081:80' # exposed for debugging and local frontend development without python
    environment:
      - DB_HOST=ca-aerooffers-db
      - DB_PORT=5432
      - DB_NAME=aircraft_offers
      - DB_USER=aircraft_offers
      - DB_PW=aircraft_offers
    depends_on:
      - ca-aerooffers-db
      - flyway

  ca-aerooffers-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=aircraft_offers
      - POSTGRES_USER=aircraft_offers
      - POSTGRES_PASSWORD=aircraft_offers
    ports:
      - '25432:5432'

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://ca-aerooffers-db:5432/aircraft_offers -user=aircraft_offers -password=aircraft_offers migrate
    volumes:
      - ./db/migrations:/flyway/sql
    depends_on:
      - ca-aerooffers-db