---
# This playbook will install PostgreSQL and create db user and give permissions.
- name: Install PostgreSQL package
  ansible.builtin.dnf:
    name: 
      - postgresql15
      - postgresql15-server
      - python3-psycopg2
    state: latest

- name: Find out if PostgreSQL is initialized
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data

- name: Initialize PostgreSQL
  shell: "postgresql-setup initdb"
  when: not postgres_data.stat.exists

- name: Update pg_hba.conf
  copy:
    src: pg_hba.conf
    dest: /var/lib/pgsql/data
    owner: postgres
    group: postgres
    mode: 0600

- name: Start PostgreSQL Service
  service:
    name: postgresql
    state: started
    enabled: yes

- name: create postgresql user
  postgresql_user:
    user: aircraftoffers
    # put your database password here...
    password: "redacted"
    expires: infinity
  become: true
  become_user: postgres

- name: create postgresql db
  postgresql_db:
    name: aircraft_offers
    owner: aircraftoffers
    state: present
  become: true
  become_user: postgres

- name: GRANT ALL to aircraftoffers
  community.postgresql.postgresql_privs:
    type: database
    db: aircraft_offers
    state: present
    privs: ALL
    role: aircraftoffers
  become: true
  become_user: postgres

- name: Reload PostgreSQL service
  service:
    name: postgresql
    state: restarted
    enabled: yes
  become: true