- name: "python3, gcc, etc (needed for uwsgi)"
  ansible.builtin.dnf:
    name: 
      - "python3"
      - "python3-devel"
      - "python3-pip"
      - "gcc"
      - "gcc-c++"
      - "make"
      - "cronie"
    state: "latest"
  become_user: root
  become_method: sudo
  become: yes

- name: "Create directory for sourcecode"
  file:
    path: "{{ code_dir }}"
    state: directory
    owner: ec2-user
  become_user: root
  become_method: sudo
  become: yes
