#!/bin/sh

echo "Formatting and fixing linter issues for backend"
cd backend
uvx ruff format
uvx ruff check --fix
git add src tests

cd ../ui
npm run lint-fix
git add src

cd ../terraform
if [ -n "$(git diff --cached --name-only -- '*.tf' '*.tfvars')" ]; then
  echo "Formatting Terraform files"
  terraform fmt
  git add .
fi