name: CD - UI

on:
  push:
    branches: [ main ]
    paths:
      - ui/**
  pull_request:
    branches: [ main ]
    paths:
      - ui/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Setup node_modules cache
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: 'Install dependencies'
        working-directory: ./ui
        run: npm install

      - name: 'Static analysis (esLint) and formatting checks'
        working-directory: ./ui
        run: npm run lint

      - name: 'Run tests'
        working-directory: ./ui
        run: CI=true npm run test:unit

      - name: 'Build VueJS app'
        working-directory: ./ui
        run: npm run build

      - name: 'Archive dist artifacts'
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: ui-dist
          path: ui/dist

  deploy:
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/main'
    needs:
      - build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: 'Download dist artifacts'
        uses: actions/download-artifact@v5
        with:
          name: ui-dist
          path: ui/dist

      - name: 'Deploy'
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          app_location: "ui/dist"
          skip_app_build: true
          skip_api_build: true
          azure_static_web_apps_api_token: ${{ secrets.UI_AZURE_STATIC_WEB_APPS_API_TOKEN }}