name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  fronend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Frontend
        working-directory: ./frontend
        run: docker build .

  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Backend
        working-directory: ./backend
        run: docker build .