name: DB Migration

on:
  push:
    branches: [ main ]
    paths:
      - db/**
  pull_request:
    branches: [ main ]
  workflow_dispatch:
paths:


jobs:
  build-ui:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 'Test flyway migration scripts'
        working-directory: ./db
        run: |
          ./run_migrations_test.sh